# Generated by Django 3.2.9 on 2021-12-04 14:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10)),
                ('userID', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myTicket', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('myPaymentDetails', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPMSapp.profile')),
            ],
        ),
    ]
