# Generated by Django 3.2.9 on 2021-12-05 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMSapp', '0002_profile_bool_logio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myticket',
            name='myPaymentDetails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=50),
        ),
        migrations.AlterField(
            model_name='myticket',
            name='myTicket',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=10),
        ),
    ]
