# Generated by Django 3.2.9 on 2021-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMSapp', '0003_auto_20211205_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myticket',
            name='myPaymentDetails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myticket',
            name='myTicket',
            field=models.TextField(),
        ),
    ]
