# Generated by Django 3.2.9 on 2021-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMSapp', '0006_myticket_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myticket',
            name='deadline_date',
            field=models.CharField(max_length=20),
        ),
    ]
